language:
  - python

python:
  - "3.5"

sudo: required

notifications:
  webhooks: https://fathomless-fjord-24024.herokuapp.com/notify

install:
  - pip install --upgrade pip
  - pip install -r requirements.txt

script:
  - cd medical_prescription
  - python3 manage.py makemigrations
  - python3 manage.py migrate
  - coverage run manage.py test

after_success:
  - coverage
  - coverage report
  - coveralls
